######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 5 22:25:53 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += graphviewjm.h skel_edge.h skel_node.h skeleton.h window.h
SOURCES += graphviewjm.cpp \
           main.cpp \
           skel_edge.cpp \
           skel_node.cpp \
           skeleton.cpp \
           window.cpp
